### ISSUE TITLE
Bun v1.0 Blogpost

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#195]
Issue for preparation of our celebratory bun 1.0 post 🎉 🎉 🎉

**Comment by hendriknielaender** [comment]
https://www.youtube.com/watch?v=BsnCpESUEqM

**Comment by flyck** [comment]
Looking at the v1 release i see the following:
- 34 fixes
- 4 updates
- 3 docs
- 1 revert
- 4 features, with maybe the most notable being the watch-file thing, which could be hype for command-line tools

Seems to be mostly a release to make things more stable ☝🏻 similar for the release before that.

Magic mocks are also not yet supported, the test tracking issue still looks slim.

**Comment by flyck** [comment]
https://lumigo.io/blog/is-bun-the-next-big-thing-for-aws-lambda-a-thorough-investigation/

**Comment by flyck** [comment]
Didnt end up blogging
