### ISSUE TITLE
How to make trpc run with the CDK on AWS

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#210]
We solved the problem after some struggle last year.

Only a few months back, people are still wondering how to do it:
- https://discord-questions.trpc.io/m/1082437634590257288

Official docs are still small:
- https://trpc.io/docs/server/adapters/aws-lambda

**Comment by hendriknielaender** [comment]
https://www.prisma.io/docs/guides/deployment/serverless/deploy-to-aws-lambda#6-test-your-deployed-rest-api

**Comment by hendriknielaender** [comment]
I would suggest we use the recommended stack for this.
https://github.com/trpc/examples-next-prisma-starter

Let us create an example repo, where we showcase the current missing part in the docs.

**Comment by hendriknielaender** [comment]
article is published! 👍
