### ISSUE TITLE
Add code syntax highlighting for zig

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#232]
Was already merged to master 3 weeks ago: https://github.com/shikijs/shiki/commit/fc13a73a5ca48810db9175da84eb0445c5bfa5ff

But the release build is failing :D Once it is released and also updated in https://www.npmjs.com/package/@astrojs/markdown-remark, we will have beautiful zig code 🤩

**Comment by hendriknielaender** [comment]
Yes next week with astro 3.0, we should have the support 🚀 

https://github.com/withastro/astro/blob/3ad5a2a28744dc18e6d5962b53934c97a749e9d1/packages/markdown/remark/package.json#L2
