### ISSUE TITLE
Build a Clickwrap App with the Beth Stack

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#272]
Plan:
- build a clickwrap app with consent management in beth
- potentially build it out to a SaaS app

Benefits:
- Learn about Beth
- Get hands dirty with an app entirely build on bun
- Potential of passive income with SaaS app

**Comment by hendriknielaender** [comment]
Maybe add it to https://github.com/documenso/documenso
later.

**Comment by flyck** [comment]
I think we talked about it that this idea is no longer hype as a good open source solution already exists 🙌🏻
