### ISSUE TITLE
Publish new posts automatically to medium & dev.to

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#3]

**Comment by hendriknielaender** [comment]
Like you mentioned we should also publish these articles to dev.to.

We should also consider to publish new articles in Reddit (e.g: /r/programming, /r/gitlab ....) and hackernews.

What do you think?

**Comment by flyck** [comment]
https://github.com/sinedied/publish-devto this one uses the devto cli which is nice
but on the downside it will need to generate files and make a new commit for them as they need to be stored somewhere / in this repo 💩 

seems like a shitty workflow but should be fine if its in a dedicated directory.

To configure this i will need access to the secrets section of the repo to set new secrets.

**Comment by flyck** [comment]
We somehow dropped this idea as it is also unclear if cross-posting is that much useful
