### ISSUE TITLE
Blog: How to build a party todo app in one weekend

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#319]
Similar to the article from yan cui and just to flex some muscles and stay fresh on fullstack app building skills. Build a party task manager in one weekend.

For the situation that you are planning a party with a group of people via whatsapp and the todolist is all over the place. Once central place to plan a party when people plan a party collaboratively.

If we build this next weekend I can use this for my friends 30s birthdate where 15 people try to plan a (surprise) party together 😆 

Features: 
- Shareable links (no login)
- list of tasks as centerpiece
  - task can be assigned to multiple party members, have a a deadline, budget, etc.

Nextjs Shadcn UI appsync dynamodb

**Comment by hendriknielaender** [comment]
Maybe in combination with `htmx` and `zig` 😅

**Comment by flyck** [comment]
Building something meaningful in one weekend while trying a bunch of new technologies did not turn out to be realistic.

Once we have the party task planner done with vercel and appsync subscriptions we can make a blog about doing the same thing simple with htmx plus something else but that also probably wont finish in one weekend. Hence closing this issue
