### ISSUE TITLE
Make background more exciting

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#332]
Ideas:
- https://codepen.io/hylobates-lar/pen/qBbQeON
- https://www.svgbackgrounds.com/ paywalled 🤮

**Comment by hendriknielaender** [comment]
created a PR for the background, maybe you find a better background pattern here: https://heropatterns.com/

**Comment by hendriknielaender** [comment]
https://github.com/hendriknielaender/double-trouble/pull/390
