### ISSUE TITLE
Guideline/Checklist/Best pratice on API Design

### ISSUE THREAD

**Issue by hendriknielaender** [hendriknielaender/double-trouble#400]
In the wild you find a lot of post about API design and best practice. 
But a more comprehend guide, which is not too long. You can't really find.

Quick examples like:
`api/customers/:id/`
- do **not** use integer ids (guessable)
- go with something like `UUID`, but with prefix `cus_23lksjdg3`
https://github.com/jetpack-io/typeid

endpoints:
- avoid nesting that is more than 3 levels deep `posts/:id/comments`

documentation:
- open api specs

errors:
https://apisyouwonthate.com/blog/useful-api-errors-for-rest-graphql-and-grpc/

versioning:
implement versioning with rolling versions that are named with the date they’re released (for example, 2017-05-24). Although backwards-incompatible, each one contains a small set of changes that make incremental upgrades relatively easy so that integrations can stay current.

Performance:
- gzip
- pagination, filtering, sorting
- caching
- rate limit & throttling 

ai:
https://apisyouwonthate.com/blog/ai-powered-api-linting-with-optic/

**Comment by flyck** [comment]
Also add an example for our best practice cloudwatch devops

**Comment by flyck** [comment]
Test
