### ISSUE TITLE
Docker vs Ephemeral Stacks

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#430]
Possible Title: The case against docker?

- Ephemeral Stacks vs Localstack & Docker, Pros and Cons
- Show example for review apps for apis (so far we only have an article for frontend review apps)
- Review Apps in AWS can easily be forwarded to PMs and commented
- Peace of mind, simplicity: Ephemeral stacks are easy
- Cons
  - Docker: relative maintenance effort

**Comment by hendriknielaender** [comment]
https://theburningmonk.com/2019/09/why-you-should-use-temporary-stacks-when-you-do-serverless/

https://theburningmonk.com/2023/02/how-to-handle-serverful-resources-when-using-ephemeral-environments/

https://theburningmonk.com/2022/05/my-testing-strategy-for-serverless-applications
