### ISSUE TITLE
Add a view counter

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#72]
Might be cool to add a view counter for each post? 😃 
![image](https://user-images.githubusercontent.com/11775168/227858905-2164e6f6-93a5-4dac-ab10-3d59dfd8b6c0.png)

**Comment by flyck** [comment]
Found an even better example
![20231104_140853](https://github.com/hendriknielaender/double-trouble/assets/11775168/a2596212-38e1-4aa2-91bf-13a9412d5679)

**Comment by hendriknielaender** [comment]
Oh yeah! That looks nice 🙂
