### ISSUE TITLE
New Post: Product Engineers

### ISSUE THREAD

**Issue by flyck** [hendriknielaender/double-trouble#9]

**Comment by flyck** [comment]
https://blog.statsig.com/5-features-to-10x-experiment-velocity-33c2cb74b61e vielleicht interessant für diese Serie

**Comment by hendriknielaender** [comment]
![colleagues](https://user-images.githubusercontent.com/51416554/216675448-392110a1-f25d-4369-8c6e-4539c7873f0f.png)
![colleagues2](https://user-images.githubusercontent.com/51416554/216675462-9784ff4b-8eeb-4649-9831-e0015587080f.png)

mhh used dall-e for it with following prompts:
1. two colleagues in front of a computer, digital art
2. two colleagues fist bumps each other in front of a computer, digital art

**Comment by hendriknielaender** [comment]
https://github.com/hendriknielaender/double-trouble/pull/10/commits/11e99d6dc2d7cfe79d1d128e0fd4592082fba7c2

added some text to the article, please have a look

**Comment by flyck** [comment]
added some more meat 🍖 to the core sections. Seems this is not enough though and will need more work 😆 

Looking at it now I'm also fine to release it as one big blogpost as well. With the whole list of other posts we have already in mind, we wouldn't have to spread this one out.
